services:
  - type: web
    name: untit7led-eid
    runtime: node
    rootDir: New folder
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: WALLET_NUMBER
        value: "01016380970"
      - key: PRODUCT_PRICE
        value: "100"
      - key: MIN_PAYMENT_AMOUNT
        value: "90"
      - key: NODE_VERSION
        value: "20"
